/** Lead source options for booking Reference field (create + edit). */
export const BOOKING_REFERENCE_OPTIONS = [
  'Website',
  'Google',
  'Play Store',
  'Previous Client',
  'Facebook',
  'YouTube',
  'LinkedIn',
  'SMS',
  'Calling Data',
  'Instagram',
  'WhatsApp',
  'Justdial',
  'Poster',
  'Friend Reference',
  'No Parking Board',
  'Holding',
  'Other',
] as const;
